baseurl = "http://code.matsu.io/"
languageCode = "en-us"
title = "code.matsu"

uglyurls = true

hasCJKLanguage = true
disableSitemap = true

[Params]
  DateForm = "2006-01-02"

[blackfriday]
  smartpants = false
  plainIDAnchors = true
