baseurl = "http://blog.matsu.io/"
languageCode = "en-us"
title = "Pine Wu's Blog"

uglyurls = true

hasCJKLanguage = true
disableKinds = ["sitemap"]

[Params]
  DateForm = "2006-01-02"

[blackfriday]
  smartypants = false
  plainIDAnchors = true

